spring:
  datasource:
    url: jdbc:h2:mem:gstecdb
    username: samuel
    password: 1234
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

  h2:
    console:
      enable: true
      path: /h2